---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

## NOAA data

```{r set up, include=FALSE}
library(tidyverse)
library(dplyr)
library(rnoaa)
library(p8105.datasets)
library(plotly)
```

```{r data, include=FALSE}
#loading data
data = 
  ny_noaa |> 
  drop_na() |> 
  separate(date, into = c("year", "month", "day"), "-") |> 
  mutate(
    tmax = as.numeric(tmax),
    tmin = as.numeric(tmin),
    prcp = as.numeric(prcp),
    snow = as.numeric(snow)
  ) |> 
  filter(year == 2000:2010) |> 
  group_by(year, month) |> 
  summarize(
    mean_prcp = mean(prcp),
    mean_snow = mean(snow),
    mean_tmax = mean(tmax),
    mean_tmin = mean(tmin)
  ) |> 
  mutate(
    month = case_when(
       month %in% c("01") ~ "Jan",
       month %in% c("02") ~ "Feb",
       month %in% c("03") ~ "Mar",
       month %in% c("04") ~ "Apr",
       month %in% c("05") ~ "May",
       month %in% c("06") ~ "Jun",
       month %in% c("07") ~ "Jul",
       month %in% c("08") ~ "Aug",
       month %in% c("09") ~ "Sep",
       month %in% c("10") ~ "Oct",
       month %in% c("11") ~ "Nov",
       month %in% c("12") ~ "Dec"),
    month = factor(month, levels = c(
        "Jan", "Feb", "Mar", "Apr", "May", "Jun",
        "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")))
```


Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
data |> 
  plot_ly(y = ~mean_tmax, color = ~year, type = "box", colors = "viridis") |> 
  layout(title = "Average Mean Maximum Temperatures in New York (2000-2010)",
         xaxis = list(title = "Year"),
         yaxis = list (title = "Mean Max Temperature"))
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
data |> 
  mutate(
    text_label = str_c(
      "mean rain: ", mean_prcp,
      "\n mean snow: ", mean_snow)) |> 
  plot_ly(
    x = ~month, y = ~mean_tmin, color = ~year, text = ~text_label,
    type = "scatter", mode = "markers", alpha = 0.5, colors = "viridis") |> 
  layout(title = "Average Mean Minimum Temperatures in New York (2000-2010)",
         xaxis = list(title = "Months"),
         yaxis = list (title = "Mean Min Temperature"))
```

### Chart C

```{r}
data |> 
  mutate(year = fct_reorder(year, mean_prcp)) |> 
  plot_ly(x= ~month, y = ~mean_prcp, color = ~year, type = "scatter",
          mode = "lines", colors = "viridis") |> 
  layout(title = "Average Precipitation in New York (2000-2010)",
         xaxis = list(title = "Year"),
         yaxis = list (title = "Mean Precipitation"))
```



